### ISSUE TITLE
hide all intermediates not completely？有些子标签下的笔记会重复显示一遍？

### ISSUE THREAD

**Issue by zhuo-lu** [vrtmrz/obsidian-tagfolder#31]
![image](https://user-images.githubusercontent.com/109290203/183416173-61a445b9-3a5b-4351-b2e3-6914083cb7f5.png)

**Comment by zhuo-lu** [comment]
when I choose hide only intermediates of nested tags,threre will be show:
![image](https://user-images.githubusercontent.com/109290203/183541616-2c860ed7-967f-4066-8afa-9fd71b6e10ad.png)
when I choose hide all intermediates ,threre will be show:
![image](https://user-images.githubusercontent.com/109290203/183541554-ee216ee9-5303-4350-a58b-4afba240cbe3.png)

**Comment by vrtmrz** [comment]
Thank you for your report! 
Perhaps it has been solved on v0.14.1, (Before 0.14, there were some bugs about the redundant tree)
Could you please check the latest version?

**Comment by zhuo-lu** [comment]
thanks for your attention！
but the latest version haven't solve my problem, and it seems to have some new problems.
- there are still some notes that are repeated under this tag.
![image](https://user-images.githubusercontent.com/109290203/184475066-8f76027b-2bb0-4eda-84fc-d1e742359be6.png)
![image](https://user-images.githubusercontent.com/109290203/184475460-1cd3144e-7b51-43ab-b8a5-d66c2597e29d.png)
- some names of some tags are confusing.
![image](https://user-images.githubusercontent.com/109290203/184474997-afbad40a-b534-45a1-925d-32168b4cb570.png)
I admire the idea of tagfolder. this plugin is the embodiment of the new idea of note management, and no one has tried.
you don't have to rush to modify them, we'll be patient for this hopeful plugin.
sorry for my bad English.

**Comment by vrtmrz** [comment]
Do not worry about English! My English is also terrrible.
The second image can be solved with `Merge redundant combinations`.
But the first one looks like be complicated, could you make reproducible files?
(Just a list of related files and the tags in them is fine!)

> I admire the idea of tagfolder. this plugin is the embodiment of the new idea of note management, and no one has tried.
you don't have to rush to modify them, we'll be patient for this hopeful plugin.

I am really honoured to hear that! Thank you for using this plugin!

**Comment by zhuo-lu** [comment]
I create a new vault to check it，the problem is still.
hope you can fix it.
[zhuolu.zip](https://github.com/vrtmrz/obsidian-tagfolder/files/9332938/zhuolu.zip)

**Comment by vrtmrz** [comment]
Thank you for your archive!
I wonder if it had reproduced... (Yes, I saw the display collapse, but it did not happen again.).
But v0.14.3 looks like working fine. Could you please try it?

**Comment by zhuo-lu** [comment]
sorry the problem remains, it must be a puzzling puzzle.
but here are some cases for reference.
- I set the Level 1 limit,and other limit did not encounter such a situation.
- when I modify the tag ，the tagfoder list will flash hidden notes until reopening this tagfolder.
- when I try other hide options, sometimes the effect has to reopen that tagfolder to achieve.
- I have tried uninstalling and reinstalling,but the problem is still.

**Comment by zhuo-lu** [comment]
Today I try some other settings,when I choose "no limit" and"hide only intermediates of nested tags", it shows as well as I want.
I used to choose "level 1"and "hide all intermediates", sometimes it shows not very well.
so strange. but the problem is solved by changing settings.

**Comment by vrtmrz** [comment]
Thank you for the detailed information.
It looks like Limiting levels, merging tags and hiding intermediates are not working in some combination.
I will investigate it!
